### ISSUE TITLE
500 errors key_error

### ISSUE THREAD

**Issue by rsmith013** [cedadev/archive_browser#62]
http://data.ceda.ac.uk/api/file/badc/cmip6/data/CMIP6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp585/r1i1p1f1/Amon/tas/gn/v20190710/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc

> [ERROR] [2020-09-09 10:10:53,706] [django.request:228] [waitress-2] Internal Server Error: /api/file/badc/cmip6/data/CMIP6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR/ssp585/r1i1p1f1/Amon/tas/gn/v20190710/tas_Amon_MPI-ESM1-2-LR_ssp585_r1i1p1f1_gn_201501-203412.nc
Traceback (most recent call last):
  File "/usr/local/archive_browser/venv/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/archive_browser/venv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/archive_browser/venv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/local/archive_browser/src/archive_browser/browser/utils/view_utils.py", line 50, in wrapper
    res = func(*args, **kwargs)
  File "/usr/local/archive_browser/src/archive_browser/browser/utils/view_utils.py", line 36, in wrapper
    res = func(*args, **kwargs)
  File "/usr/local/archive_browser/src/archive_browser/browser/views.py", line 136, in get_files
    archive_path = first_result['archive_path']
KeyError: 'archive_path'

**Comment by spepler** [comment]
Not a problem for the reindexed version.
